// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TrainingMonitor.Data;

#nullable disable

namespace TrainingMonitor.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260723064900_SyncSnakeCaseNaming")]
    partial class SyncSnakeCaseNaming
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TrainingMonitor.Models.Entities.Category", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("unit");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.ToTable("categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Description = "3km 구간 완주 시간 (초 단위)",
                            IsActive = true,
                            Name = "3km 달리기",
                            Unit = "초"
                        },
                        new
                        {
                            Id = 2L,
                            Description = "2분 내 최대 횟수",
                            IsActive = true,
                            Name = "팔굽혀펴기",
                            Unit = "회"
                        },
                        new
                        {
                            Id = 3L,
                            Description = "2분 내 최대 횟수",
                            IsActive = true,
                            Name = "윗몸일으키기",
                            Unit = "회"
                        });
                });

            modelBuilder.Entity("TrainingMonitor.Models.Entities.GradeCriteria", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("category_id");

                    b.Property<string>("Gender")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("gender");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("grade");

                    b.Property<double?>("MaxValue")
                        .HasColumnType("double precision")
                        .HasColumnName("max_value");

                    b.Property<double?>("MinValue")
                        .HasColumnType("double precision")
                        .HasColumnName("min_value");

                    b.Property<string>("RankGroup")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("rank_group");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_grade_criteria");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_grade_criteria_category_id");

                    b.ToTable("grade_criteria", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CategoryId = 1L,
                            Grade = "특급",
                            MaxValue = 720.0,
                            RankGroup = "병사",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2L,
                            CategoryId = 1L,
                            Grade = "1급",
                            MaxValue = 780.0,
                            RankGroup = "병사",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3L,
                            CategoryId = 1L,
                            Grade = "2급",
                            MaxValue = 900.0,
                            RankGroup = "병사",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4L,
                            CategoryId = 1L,
                            Grade = "3급",
                            MaxValue = 960.0,
                            RankGroup = "병사",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 5L,
                            CategoryId = 1L,
                            Grade = "불합격",
                            RankGroup = "병사",
                            SortOrder = 5
                        });
                });

            modelBuilder.Entity("TrainingMonitor.Models.Entities.MeasurementSession", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("AdminId")
                        .HasColumnType("bigint")
                        .HasColumnName("admin_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("location");

                    b.Property<DateOnly>("MeasuredAt")
                        .HasColumnType("date")
                        .HasColumnName("measured_at");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<long?>("UnitId")
                        .HasColumnType("bigint")
                        .HasColumnName("unit_id");

                    b.HasKey("Id")
                        .HasName("pk_measurement_sessions");

                    b.HasIndex("AdminId")
                        .HasDatabaseName("ix_measurement_sessions_admin_id");

                    b.HasIndex("UnitId")
                        .HasDatabaseName("ix_measurement_sessions_unit_id");

                    b.ToTable("measurement_sessions", (string)null);
                });

            modelBuilder.Entity("TrainingMonitor.Models.Entities.Record", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Grade")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("grade");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<long?>("SessionId")
                        .HasColumnType("bigint")
                        .HasColumnName("session_id");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<double>("Value")
                        .HasColumnType("double precision")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_records");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_records_category_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_records_user_id");

                    b.HasIndex("SessionId", "UserId", "CategoryId")
                        .IsUnique()
                        .HasDatabaseName("ix_records_session_id_user_id_category_id");

                    b.ToTable("records", (string)null);
                });

            modelBuilder.Entity("TrainingMonitor.Models.Entities.RefreshToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("token");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("TrainingMonitor.Models.Entities.Unit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint")
                        .HasColumnName("parent_id");

                    b.HasKey("Id")
                        .HasName("pk_units");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_units_parent_id");

                    b.ToTable("units", (string)null);
                });

            modelBuilder.Entity("TrainingMonitor.Models.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("MilitaryId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("military_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Rank")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("rank");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<long?>("UnitId")
                        .HasColumnType("bigint")
                        .HasColumnName("unit_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("MilitaryId")
                        .IsUnique()
                        .HasDatabaseName("ix_users_military_id");

                    b.HasIndex("UnitId")
                        .HasDatabaseName("ix_users_unit_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("TrainingMonitor.Models.Entities.GradeCriteria", b =>
                {
                    b.HasOne("TrainingMonitor.Models.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_grade_criteria_categories_category_id");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("TrainingMonitor.Models.Entities.MeasurementSession", b =>
                {
                    b.HasOne("TrainingMonitor.Models.Entities.User", "Admin")
                        .WithMany()
                        .HasForeignKey("AdminId")
                        .HasConstraintName("fk_measurement_sessions_users_admin_id");

                    b.HasOne("TrainingMonitor.Models.Entities.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .HasConstraintName("fk_measurement_sessions_units_unit_id");

                    b.Navigation("Admin");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("TrainingMonitor.Models.Entities.Record", b =>
                {
                    b.HasOne("TrainingMonitor.Models.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_records_categories_category_id");

                    b.HasOne("TrainingMonitor.Models.Entities.MeasurementSession", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .HasConstraintName("fk_records_measurement_sessions_session_id");

                    b.HasOne("TrainingMonitor.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_records_users_user_id");

                    b.Navigation("Category");

                    b.Navigation("Session");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TrainingMonitor.Models.Entities.RefreshToken", b =>
                {
                    b.HasOne("TrainingMonitor.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TrainingMonitor.Models.Entities.Unit", b =>
                {
                    b.HasOne("TrainingMonitor.Models.Entities.Unit", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .HasConstraintName("fk_units_units_parent_id");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("TrainingMonitor.Models.Entities.User", b =>
                {
                    b.HasOne("TrainingMonitor.Models.Entities.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .HasConstraintName("fk_users_units_unit_id");

                    b.Navigation("Unit");
                });
#pragma warning restore 612, 618
        }
    }
}
